spring:
  profiles:
    active: local # default (prod로 바꿔 실행하면 The following 2 profiles are active: "prod", "common" 으로 나온다.
    group:
      local: # local, common profile 실행
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

# ...

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate  #운영에서는 none, validate 사용
    show-sql: true # 쿼리 보기 위해

pharmacy:
  recommendation:
    base:
      url: http://localhost:8080/dir/

---
spring:
  config:
    activate:
      on-profile: prod
